# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- original

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'windows-latest'
    steps:

    - task: CopyFiles@2
      displayName: 'Copy scripts'
      inputs:
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: armtemplate

- stage: test
  dependsOn: build
  jobs:
  - job: run_test
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'windows-latest'

    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: armtemplate
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Assinatura do Visual Studio Enterprise – MPN(5)(8bc9e0b7-9ad7-4b73-aa86-c78a8cfe10b3)'
        subscriptionId: '8bc9e0b7-9ad7-4b73-aa86-c78a8cfe10b3'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'azuretjsprg'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/azuredeploy.json'
        csmParametersFile: '$(Pipeline.Workspace)/azuredeploy.parameters.json'
        deploymentMode: 'Incremental'