trigger:
- main

pool:
  vmImage: windows-latest

jobs:
  - job: removeSPSESingleFarm
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 1
    steps:
    - script:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'ARM Conn'
        subscriptionId: 'bed82fbc-918c-4d3c-915a-a571bec7ee87'
        action: 'DeleteRG'
        resourceGroupName: 'tjsprg'

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'ARM Conn'
        subscriptionId: 'bed82fbc-918c-4d3c-915a-a571bec7ee87'
        action: 'DeleteRG'
        resourceGroupName: 'NetworkWatcherRG'
